//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_site_visits
    {
        public int uniq_id { get; set; }
        public string tbl_conf { get; set; }
        public string tbl_conf_id { get; set; }
        public string tbl_ip { get; set; }
        public string tbl_country { get; set; }
        public string tbl_region { get; set; }
        public string tbl_city { get; set; }
        public string tbl_browser { get; set; }
        public System.DateTime tr_date { get; set; }
    }
}
