//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int access { get; set; }
        public string conf_name { get; set; }
        public string conf_id { get; set; }
        public string user_mail { get; set; }
        public string user_name { get; set; }
        public System.DateTime tr_date { get; set; }
    }
}
