//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_event_contact
    {
        public string tbl_conf { get; set; }
        public string conf_id { get; set; }
        public string tbl_mail_name1 { get; set; }
        public string tbl_mail_1 { get; set; }
        public string tbl_mail_name2 { get; set; }
        public string tbl_mail_2 { get; set; }
        public string tbl_mail_name3 { get; set; }
        public string tbl_mail_3 { get; set; }
        public string tbl_contact_name1 { get; set; }
        public string tbl_contact_1 { get; set; }
        public string tbl_contact_name2 { get; set; }
        public string tbl_contact_2 { get; set; }
        public string tbl_contact_name3 { get; set; }
        public string tbl_contact_3 { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
