//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_site_contact
    {
        public int uniq_id { get; set; }
        public string msg_name { get; set; }
        public string msg_mail { get; set; }
        public string msg_subject { get; set; }
        public string msg_message { get; set; }
        public string msg_ip { get; set; }
        public string msg_browser { get; set; }
        public System.DateTime tr_date { get; set; }
        public int Id_new { get; set; }
    }
}
