//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_part_reg
    {
        public string tbl_user_name { get; set; }
        public string tbl_conf { get; set; }
        public string tbl_conf_id { get; set; }
        public string tbl_txn_id { get; set; }
        public string tbl_pack_a { get; set; }
        public string tbl_pack_b { get; set; }
        public string tbl_pack_c { get; set; }
        public string tbl_company { get; set; }
        public string tbl_city { get; set; }
        public string tbl_state { get; set; }
        public string tbl_country { get; set; }
        public string tbl_mail { get; set; }
        public string tbl_phone { get; set; }
        public string tbl_address { get; set; }
        public string tbl_cat { get; set; }
        public string tbl_talk { get; set; }
        public string tbl_currency { get; set; }
        public Nullable<decimal> tbl_grand_total { get; set; }
        public string tbl_reg_stastus { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
