//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_newsletter
    {
        public string nl_name { get; set; }
        public string nl_mail { get; set; }
        public string nl_phone { get; set; }
        public string nl_intrest { get; set; }
        public string nl_ip { get; set; }
        public string nl_browser { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
