//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_conference
    {
        public string con_title { get; set; }
        public Nullable<System.DateTime> con_date { get; set; }
        public string con_place { get; set; }
        public string con_theme { get; set; }
        public string con_left_logo { get; set; }
        public string con_right_logo { get; set; }
        public string con_banner { get; set; }
        public string con_subject { get; set; }
        public string con_subject_id { get; set; }
        public string con_country { get; set; }
        public string con_country_id { get; set; }
        public string con_contact_desk { get; set; }
        public string con_opt_1 { get; set; }
        public string con_opt_2 { get; set; }
        public string con_opt_3 { get; set; }
        public string con_opt_4 { get; set; }
        public string con_opt_5 { get; set; }
        public string con_opt_6 { get; set; }
        public string con_t { get; set; }
        public string con_b { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
