//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faq
    {
        public string tbl_question { get; set; }
        public string tbl_answer { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
