//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_event_buttons
    {
        public string tbl_conf { get; set; }
        public string tbl_conf_id { get; set; }
        public string tbl_summary { get; set; }
        public string tbl_imp_dates { get; set; }
        public string tbl_call_paper { get; set; }
        public string tbl_market_anly { get; set; }
        public string tbl_broucher { get; set; }
        public string tbl_imp_links { get; set; }
        public string tbl_venue { get; set; }
        public string tbl_contact { get; set; }
        public string tbl_eposter { get; set; }
        public string tbl_evideo { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
