//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pack_reg
    {
        public string tbl_conf { get; set; }
        public string conf_id { get; set; }
        public string tbl_pack { get; set; }
        public string pack_id { get; set; }
        public string pack_name { get; set; }
        public string pack_desc { get; set; }
        public Nullable<System.DateTime> date_1 { get; set; }
        public Nullable<System.DateTime> date_2 { get; set; }
        public Nullable<System.DateTime> date_3 { get; set; }
        public Nullable<decimal> gbp_1 { get; set; }
        public Nullable<decimal> gbp_2 { get; set; }
        public Nullable<decimal> gbp_3 { get; set; }
        public Nullable<decimal> euro_1 { get; set; }
        public Nullable<decimal> euro_2 { get; set; }
        public Nullable<decimal> euro_3 { get; set; }
        public Nullable<decimal> usd_1 { get; set; }
        public Nullable<decimal> usd_2 { get; set; }
        public Nullable<decimal> usd_3 { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
