//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_conf_abstract
    {
        public string tbl_title { get; set; }
        public string tbl_fname { get; set; }
        public string tbl_lname { get; set; }
        public string tbl_country { get; set; }
        public string tbl_mail { get; set; }
        public string tbl_phone { get; set; }
        public string tbl_cat { get; set; }
        public string tbl_track { get; set; }
        public string tbl_address { get; set; }
        public string tbl_file { get; set; }
        public string conf_name { get; set; }
        public string conf_id { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
