//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eposter
    {
        public string ogc_name { get; set; }
        public string ogc_desg { get; set; }
        public string ogc_place { get; set; }
        public string ogc_bio { get; set; }
        public string ogc_research { get; set; }
        public string ogc_photo { get; set; }
        public string ogc_conference { get; set; }
        public string ogc_university { get; set; }
        public string conf_id { get; set; }
        public System.DateTime tr_date { get; set; }
        public int uniq_id { get; set; }
    }
}
