//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paypal_payments
    {
        public int id { get; set; }
        public string txnid { get; set; }
        public decimal payment_amount { get; set; }
        public string payment_status { get; set; }
        public string itemid { get; set; }
        public System.DateTime createdtime { get; set; }
        public int uniq_id { get; set; }
    }
}
