//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_videos
    {
        public int uniq_id { get; set; }
        public string vid_owner { get; set; }
        public string vid_desc { get; set; }
        public string vid_topic { get; set; }
        public string vid_place { get; set; }
        public string vid_date { get; set; }
        public string vid_source { get; set; }
        public string tbl_conf { get; set; }
        public string tbl_conf_id { get; set; }
        public System.DateTime tr_date { get; set; }
    }
}
